codecov:
  branch: master

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        if_ci_failed: success

comment:
  layout: "header, diff, changes, uncovered, tree"
  behavior: default
