pipeline:
  clone:
    image: plugins/git
    depth: 1
  postgres10-php5.6:
    image: nextcloudci/php5.6:php5.6-7
    commands:
      - sleep 10 # gives the database enough time to initialize
      - NOCOVERAGE=true TEST_SELECTION=DB ./autotest.sh pgsql10
#    when:
#      matrix:
#        DB: postgres10
#        PHP: 5.6
matrix:
  include:
    - DB: postgres10
      PHP: 5.6
      ENABLE_REDIS: true

services:
  cache:
    image: redis
    when:
      matrix:
       ENABLE_REDIS: true
  postgres10:
    image: postgres:10-alpine
    environment:
      - POSTGRES_USER=oc_autotest
      - POSTGRES_PASSWORD=owncloud
#    when:
#      matrix:
#        DB: postgres10
