build:
  jsunit:
    image: nextcloudci/jsunit:1.0.6
    commands:
      - ./autotest-js.sh
    when:
      matrix:
        #TESTS: jsunit
        DB: NODB
        PHP: 5.6
  nodb-php5.6:
    image: nextcloudci/php5.6:php5.6-2
    commands:
      - git submodule update --init
      - NOCOVERAGE=true TEST_SELECTION=NODB ./autotest.sh sqlite
    when:
      matrix:
        DB: NODB
        PHP: 5.6
  nodb-php7.0:
    image: nextcloudci/php7.0:php7.0-2
    commands:
      - git submodule update --init
      - NOCOVERAGE=true TEST_SELECTION=NODB ./autotest.sh sqlite
    when:
      matrix:
        DB: NODB
        PHP: 7.0
  nodb-php7.1:
    image: nextcloudci/php7.1:php7.1-3
    commands:
      - git submodule update --init
      - NOCOVERAGE=true TEST_SELECTION=NODB ./autotest.sh sqlite
    when:
      matrix:
        DB: NODB
        PHP: 7.1
  sqlite-php5.6:
    image: nextcloudci/php5.6:php5.6-2
    commands:
      - git submodule update --init
      - NOCOVERAGE=true TEST_SELECTION=DB ./autotest.sh sqlite
    when:
      matrix:
        DB: sqlite
        PHP: 5.6
  sqlite-php7.0:
    image: nextcloudci/php7.0:php7.0-2
    commands:
      - git submodule update --init
      - NOCOVERAGE=true TEST_SELECTION=DB ./autotest.sh sqlite
    when:
      matrix:
        DB: sqlite
        PHP: 7.0
  sqlite-php7.1:
    image: nextcloudci/php7.1:php7.1-3
    commands:
      - git submodule update --init
      - NOCOVERAGE=true TEST_SELECTION=DB ./autotest.sh sqlite
    when:
      matrix:
        DB: sqlite
        PHP: 7.1
  mysql-php5.6:
    image: nextcloudci/php5.6:php5.6-2
    commands:
      - sleep 15 # gives the database enough time to initialize
      - git submodule update --init
      - NOCOVERAGE=true TEST_SELECTION=DB ./autotest.sh mysql
    when:
      matrix:
        #DB: mysql
        #PHP: 5.6
        DB: NODB
        PHP: 7.0
  postgres-php5.6:
    image: nextcloudci/php5.6:php5.6-2
    commands:
      - sleep 10 # gives the database enough time to initialize
      - git submodule update --init
      - NOCOVERAGE=true TEST_SELECTION=DB ./autotest.sh pgsql
    when:
      matrix:
        #DB: postgres
        DB: sqlite
        PHP: 7.0
  integration:
    image: nextcloudci/php7.0:php7.0-2
    commands:
      - git submodule update --init
      - ./occ maintenance:install --admin-pass=admin
      - cd build/integration
      - ./run.sh
    when:
      matrix:
        #TESTS: integration
        DB: NODB
        PHP: 7.1

matrix:
  DB:
    - NODB
    - sqlite
  PHP:
    - 5.6
    - 7.0
    - 7.1
#  include:
#    - TESTS: jsunit - not possible in 0.4 -> runs during NODB 5.6
#    - DB: mysql - not possible in 0.4 -> runs during NODB 7.0
#      PHP: 5.6
#    - DB: postgres - not possible in 0.4 -> runs during sqlite 7.0
#      PHP: 5.6
#    - TESTS: integration - not possible in 0.4 -> runs during NODB 7.1

compose:
  cache:
    image: redis
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=oc_autotest
      - POSTGRES_PASSWORD=oc_autotest
    when:
      matrix:
        #DB: postgres
        DB: sqlite
        PHP: 7.0
  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=owncloud
      - MYSQL_USER=oc_autotest
      - MYSQL_PASSWORD=owncloud
      - MYSQL_DATABASE=oc_autotest
    when:
      matrix:
        #DB: mysql
        DB: NODB
        PHP: 7.0
