kind: pipeline
name: sqlite

steps:
- name: submodules
  image: docker:git
  commands:
    - git submodule update --init
- name: sqlite-php7.3
  image: nextcloudci/php7.3:latest
  commands:
    - bash tests/drone-run-php-tests.sh || exit 0
    - NOCOVERAGE=true TEST_SELECTION=DB ./autotest.sh sqlite
- name: sqlite-php7.4
  image: nextcloudci/php7.4:latest
  commands:
    - bash tests/drone-run-php-tests.sh || exit 0
    - NOCOVERAGE=true TEST_SELECTION=DB ./autotest.sh sqlite
#- name: sqlite-php8.0
#  image: nextcloudci/php8.0:latest
#  commands:
#    - bash tests/drone-run-php-tests.sh || exit 0
#    - NOCOVERAGE=true TEST_SELECTION=DB ./autotest.sh sqlite

services:
- name: cache
  image: redis

trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push
